resolver: lts-16.15

packages:
  - lmdb-static
  - proto
  - racquire
  - terminal-progress-bar
  - urbit-atom
  - urbit-azimuth
  - urbit-eventlog-lmdb
  - urbit-king
  - urbit-termsize
  - urbit-noun
  - urbit-noun-core

extra-deps:
  - base58-bytestring-0.1.0@sha256:a1da72ee89d5450bac1c792d9fcbe95ed7154ab7246f2172b57bd4fd9b5eab79
  - lock-file-0.7.0.0@sha256:3ad84b5e454145e1d928063b56abb96db24a99a21b493989520e58fa0ab37b00
  - para-1.1@sha256:a90eebb063ad70271e6e2a7f00a93e8e8f8b77273f100f39852fbf8301926f81

# This allows building on NixOS.
nix:
  packages:
    - pkgconfig
    - zlib

# TODO: Why is this here?
ghc-options:
  urbit-king: '-optP-Wno-nonportable-include-path'
